# you might have to
# unset VAGRANT_SERVER_URL 
# unset ATLAS_TOKEN  
Vagrant.configure("2") do |config|
  config.vm.hostname = "dash-development-ubuntu-desktop"
  config.vm.define "dash-development-ubuntu-desktop"
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.synced_folder "../../../", "/dash-code"

  config.vm.provider :virtualbox do |vb|
    vb.gui = true
    vb.name = "dash-development-ubuntu-desktop"
  
    # Use VBoxManage to customize the VM. For example to change memory:
    vb.customize ["modifyvm", :id, "--cpus", "4"]
    vb.customize ["modifyvm", :id, "--memory", "8182"]
    vb.customize ["modifyvm", :id, "--vram", "128"]
  end
  config.vm.provision "shell", path: "../../scripts/ubuntu-initial.sh"
  config.vm.provision "shell", path: "../../scripts/ubuntu-install-development-environment.sh"
  if ENV['ARTIFACTORY_API_KEY']
    config.vm.provision "shell", path: "../../scripts/ubuntu-fetch-winteracter-ccdc-private.sh", args: ENV['ARTIFACTORY_API_KEY']
  end
  # last one as it reboots
  config.vm.provision "shell", path: "../../scripts/ubuntu-install-minimal-desktop.sh"
  
end
