      MODULE FTN_C_1 
      USE, INTRINSIC :: ISO_C_BINDING 
      END MODULE FTN_C_1

      MODULE CCDC_LICENSE_BINDINGS 
      
      INTERFACE
      SUBROUTINE IS_LICENSED_OR_EXIT() BIND(C,NAME='is_dash_licensed_or_exit')
      USE FTN_C_1
      IMPLICIT NONE 
      END SUBROUTINE IS_LICENSED_OR_EXIT 
      END INTERFACE
      
      INTERFACE
      SUBROUTINE INITIALIZE_LICENSING() BIND(C,NAME='initialize_dash')
      USE FTN_C_1
      IMPLICIT NONE 
      END SUBROUTINE INITIALIZE_LICENSING 
      END INTERFACE

      INTERFACE
      SUBROUTINE FINALIZE_LICENSING() BIND(C,NAME='finalize_dash')
      USE FTN_C_1
      IMPLICIT NONE 
      END SUBROUTINE FINALIZE_LICENSING 
      END INTERFACE
      
      END MODULE CCDC_LICENSE_BINDINGS
    
    
      MODULE CCDC_EXTERNAL_APPLICATIONS_BINDINGS 
      INTERFACE
      INTEGER (C_INT) FUNCTION CCDC_LAUNCH_MERCURY(FILENAME,CLIENT_MODE) & 
      BIND(C,NAME='launch_mercury_from_dash')
      USE VARIABLES
      USE FTN_C_1
      IMPLICIT NONE 
      CHARACTER(KIND=C_CHAR), dimension(*) :: FILENAME 
      INTEGER (C_INT), VALUE :: CLIENT_MODE
      END FUNCTION CCDC_LAUNCH_MERCURY 
      END INTERFACE
      END MODULE CCDC_EXTERNAL_APPLICATIONS_BINDINGS


    