      MODULE FTN_C_1 
      USE, INTRINSIC :: ISO_C_BINDING 
      END MODULE FTN_C_1

      MODULE CCDC_LICENSE_BINDINGS 
      INTERFACE
      INTEGER (C_INT) FUNCTION CCDC_IS_LICENSED(USE_GUI) & 
      BIND(C,NAME='is_dash_licensed')
      USE FTN_C_1
      IMPLICIT NONE 
      INTEGER (C_INT), VALUE :: USE_GUI
      END FUNCTION CCDC_IS_LICENSED 
      END INTERFACE
      END MODULE CCDC_LICENSE_BINDINGS
    
    
      MODULE CCDC_EXTERNAL_APPLICATIONS_BINDINGS 
      INTERFACE
      INTEGER (C_INT) FUNCTION CCDC_LAUNCH_MERCURY(FILENAME,CLIENT_MODE) & 
      BIND(C,NAME='launch_mercury_from_dash')
      USE VARIABLES
      USE FTN_C_1
      IMPLICIT NONE 
      CHARACTER(KIND=C_CHAR), dimension(*) :: FILENAME 
      INTEGER (C_INT), VALUE :: CLIENT_MODE
      END FUNCTION CCDC_LAUNCH_MERCURY 
      END INTERFACE
      END MODULE CCDC_EXTERNAL_APPLICATIONS_BINDINGS


    