      MODULE FTN_C_1 
      USE, INTRINSIC :: ISO_C_BINDING 
      END MODULE FTN_C_1

      MODULE CCDC_LICENSE_BINDINGS 
      INTERFACE
      INTEGER (C_INT) FUNCTION CCDC_IS_LICENSED(USE_GUI) & 
      BIND(C,NAME='is_licensed')
      USE FTN_C_1
      IMPLICIT NONE 
      INTEGER (C_INT), VALUE :: USE_GUI
      END FUNCTION CCDC_IS_LICENSED 
      END INTERFACE
      END MODULE CCDC_LICENSE_BINDINGS

    