      Integer IXPos_IDD_Pawley_Status,
     &IYPos_IDD_Pawley_Status,IWidth_IDD_Pawley_Status,
     &IHeight_IDD_Pawley_Status
      Integer IXPos_IDD_SA_Input,
     &IYPos_IDD_SA_Input,IWidth_IDD_SA_Input,
     &IHeight_IDD_SA_Input
      Integer IXPos_IDD_Wizard,
     &IYPos_IDD_Wizard,IWidth_IDD_Wizard,
     &IHeight_IDD_Wizard
      common /DialoguePosCmn/ IXPos_IDD_Pawley_Status,
     &IYPos_IDD_Pawley_Status,IWidth_IDD_Pawley_Status,
     &IHeight_IDD_Pawley_Status,IXPos_IDD_SA_Input,
     &IYPos_IDD_SA_Input,IWidth_IDD_SA_Input,
     &IHeight_IDD_SA_Input,IXPos_IDD_Wizard,
     &IYPos_IDD_Wizard,IWidth_IDD_Wizard,
     &IHeight_IDD_Wizard
