!
!*****************************************************************************
!
!     --------------------------------------------------
!     | 	      T R I C L I N I C	1	       |
!     --------------------------------------------------
      SUBROUTINE TRICLINI1(Vmin,Vmax)

      USE DICVAR

      IMPLICIT NONE
!
! Dummy arguments
!
      REAL :: Vmax, Vmin
      INTENT (IN) Vmax, Vmin
!
! Local variables
!
      REAL :: Amaab, Amabc, Cma, Cmi, Dma, Dmi, Ema, Fma
      REAL, INTRINSIC :: AMAX1, AMIN1
      INTEGER :: I, Ias, Ijx, Jrt

      cxa = .01
      cxb = .01
      cxc = .01
      cxd = .01
      cxe = .01
      cxf = .01
      cya = .0015
      pasa = .0027
      pasb = .0027
      pasc = .0027
      pasd = .0027
      pase = .0027
      pasf = .0027
      n5 = 5
      n6 = 6
      zco = 1.98296076
      kt = 1
      ktp = 0
      vmax2 = Vmax**2
      vmin2 = Vmin*Vmin
      vr2 = v*v
      aas(1) = 1000.
      bbs(1) = 1000.
      ccs(1) = 1000.
      dds(1) = 1000.
      ees(1) = 1000.
      ffs(1) = 1000.
      pasa2 = pasa/2.
      pasa4 = pasa/4.
      pasa8 = pasa/8.
      pasa16 = pasa/16.
      pasa32 = pasa/32.
      pasa64 = pasa/64.
      pasb2 = pasb/2.
      pasb4 = pasb/4.
      pasb8 = pasb/8.
      pasb16 = pasb/16.
      pasb32 = pasb/32.
      pasb64 = pasb/64.
      pasc2 = pasc/2.
      pasc4 = pasc/4.
      pasc8 = pasc/8.
      pasc16 = pasc/16.
      pasc32 = pasc/32.
      pasc64 = pasc/64.
      pasd2 = pasd/2.
      pasd4 = pasd/4.
      pasd8 = pasd/8.
      pasd16 = pasd/16.
      pasd32 = pasd/32.
      pasd64 = pasd/64.
      pase2 = pase/2.
      pase4 = pase/4.
      pase8 = pase/8.
      pase16 = pase/16.
      pase32 = pase/32.
      pase64 = pase/64.
      pasf2 = pasf/2.
      pasf4 = pasf/4.
      pasf8 = pasf/8.
      pasf16 = pasf/16.
      pasf32 = pasf/32.
      pasf64 = pasf/64.
      mh = 4
      mk = 4
      ml = 4
      mh2 = 6
      mk2 = 6
      ml2 = 6
      DO Ijx = 1, 14
        DO I = 1, 8
          ndich(I) = 0
        ENDDO
        dmin = .0
        emin = .0
        fmin = .0
        jrd = 0
        Jrt = 1
        amin = q(1)/4. - epsq(1)/4.
        amax = q(4) + epsq(4)
        cmin = amin
        cmax = amax
        bmin = amin
        bmax = amax
        fmax = SQRT(zco)*amax
        emax = 2.*amax
        dmax = fmax
        md12 = 0
        md34 = 0
        md56 = 0
        md7 = 0
        md89 = 0
        jjaa = 1
        jjbb = 1
        jjcc = 1
        jjdd = 1
        jjee = 1
        jjff = 1
        iiaa = 1
        iibb = 1
        iicc = 1
        iidd = 1
        iiee = 1
        iiff = 1
        SELECT CASE (Ijx)
        CASE (2)
          irj(1,7) = 1
          amin = q(1) - epsq(1)
          amax = q(1) + epsq(1)
          kamin = coeff*amin
          kamax = coeff*amax
          amoi1 = amin
          amoi2 = amin
          amoi3 = amin
          amoi4 = amin
          amoi5 = amin
          amoi6 = amin
          amoi7 = amin
          aplu1 = amax
          aplu2 = amax
          aplu3 = amax
          aplu4 = amax
          aplu5 = amax
          aplu6 = amax
          aplu7 = amax
          kamoi1 = kamin
          kamoi2 = kamin
          kamoi3 = kamin
          kamoi4 = kamin
          kamoi5 = kamin
          kamoi6 = kamin
          kamoi7 = kamin
          kaplu1 = kamax
          kaplu2 = kamax
          kaplu3 = kamax
          kaplu4 = kamax
          kaplu5 = kamax
          kaplu6 = kamax
          kaplu7 = kamax
          s1 = q(2) - q(1)
          errd = epsq(1) + epsq(2)
          md12 = 1
          iiaa = 0
          iidd = 0
          jjaa = 0
          jjdd = 0
          dmax = AMIN1(SQRT(zco*amax*bmax),dmax)
          bmin = AMAX1((s1-errd-dmax),bmin)
          emax = AMIN1(2*SQRT(bmax*cmax),emax)
          fmax = AMIN1(SQRT(zco*amax*cmax),fmax)
          GOTO 250
        CASE (3)
          amin = q(1) - epsq(1)
          amax = q(1) + epsq(1)
          kamin = coeff*amin
          kamax = coeff*amax
          amoi1 = amin
          amoi2 = amin
          amoi3 = amin
          amoi4 = amin
          amoi5 = amin
          amoi6 = amin
          amoi7 = amin
          aplu1 = amax
          aplu2 = amax
          aplu3 = amax
          aplu4 = amax
          aplu5 = amax
          aplu6 = amax
          aplu7 = amax
          kamoi1 = kamin
          kamoi2 = kamin
          kamoi3 = kamin
          kamoi4 = kamin
          kamoi5 = kamin
          kamoi6 = kamin
          kamoi7 = kamin
          kaplu1 = kamax
          kaplu2 = kamax
          kaplu3 = kamax
          kaplu4 = kamax
          kaplu5 = kamax
          kaplu6 = kamax
          kaplu7 = kamax
          s8 = q(2)
          erre = epsq(2)
          jjee = 0
          jjaa = 0
          iiee = 0
          iiaa = 0
          md89 = 1
          dmax = AMIN1(SQRT(zco*amax*bmax),dmax)
          fmax = AMIN1(SQRT(zco*amax*cmax),fmax)
          Amabc = 2.*(AMAX1(bmax,cmax))
          cmin = AMAX1(s8-bmax-erre-Amabc,cmin)
          bmin = AMAX1(s8-cmax-erre-Amabc,bmin)
          cmax = AMIN1(cmax,s8-bmin+Amabc+erre)
          bmax = AMIN1(bmax,s8-cmin+Amabc+erre)
          dmax = AMIN1(SQRT(zco*amax*bmax),dmax)
          fmax = AMIN1(SQRT(zco*amax*cmax),fmax)
          emax = AMIN1(2*SQRT(bmax*cmax),emax)
          GOTO 250
        CASE (4)
          irj(1,7) = 1
          amax = q(1) + epsq(1)
          amin = q(1) - epsq(1)
          bmax = q(2)/4. + epsq(2)/4.
          bmin = q(2)/4. - epsq(2)/4.
          kamin = coeff*amin
          kamax = coeff*amax
          kbmin = coeff*bmin
          kbmax = coeff*bmax
          amn = (amin+amax)/2.
          bmn = (bmin+bmax)/2.
          amoi1 = amin
          amoi2 = amin
          amoi3 = amin
          amoi4 = amin
          amoi5 = amin
          amoi6 = amin
          amoi7 = amin
          aplu1 = amax
          aplu2 = amax
          aplu3 = amax
          aplu4 = amax
          aplu5 = amax
          aplu6 = amax
          aplu7 = amax
          bmoi1 = bmin
          bmoi2 = bmin
          bmoi3 = bmin
          bmoi4 = bmin
          bmoi5 = bmin
          bmoi6 = bmin
          bmoi7 = bmin
          bplu1 = bmax
          bplu2 = bmax
          bplu3 = bmax
          bplu4 = bmax
          bplu5 = bmax
          bplu6 = bmax
          bplu7 = bmax
          kamoi1 = kamin
          kamoi2 = kamin
          kamoi3 = kamin
          kamoi4 = kamin
          kamoi5 = kamin
          kamoi6 = kamin
          kamoi7 = kamin
          kaplu1 = kamax
          kaplu2 = kamax
          kaplu3 = kamax
          kaplu4 = kamax
          kaplu5 = kamax
          kaplu6 = kamax
          kaplu7 = kamax
          kbmoi1 = kbmin
          kbmoi2 = kbmin
          kbmoi3 = kbmin
          kbmoi4 = kbmin
          kbmoi5 = kbmin
          kbmoi6 = kbmin
          kbmoi7 = kbmin
          kbplu1 = kbmax
          kbplu2 = kbmax
          kbplu3 = kbmax
          kbplu4 = kbmax
          kbplu5 = kbmax
          kbplu6 = kbmax
          kbplu7 = kbmax
          iiaa = 0
          iibb = 0
          jjaa = 0
          jjbb = 0
          dmax = AMIN1(SQRT(zco*amax*bmax),dmax)
          fmax = AMIN1(SQRT(zco*amax*cmax),fmax)
          cmin = AMAX1(cmin,emin*emin/bmax/2.)
          cmin = AMAX1(cmin,fmin*fmin/amax/zco)
          emax = AMIN1(2*SQRT(bmax*cmax),emax)
          Dmi = dmin
          Dma = dmax
          Cma = cmax
          Cmi = cmin
          Fma = fmax
          Ema = emax
          CALL RELSPE
          IF ( jrd.EQ.0 ) GOTO 250
          jjdd = 0
          GOTO 100
        CASE (5)
          irj(1,7) = 1
          bmin = q(2) - epsq(2)
          bmax = q(2) + epsq(2)
          kbmin = coeff*bmin
          kbmax = coeff*bmax
          bmoi1 = bmin
          bmoi2 = bmin
          bmoi3 = bmin
          bmoi4 = bmin
          bmoi5 = bmin
          bmoi6 = bmin
          bmoi7 = bmin
          bplu1 = bmax
          bplu2 = bmax
          bplu3 = bmax
          bplu4 = bmax
          bplu5 = bmax
          bplu6 = bmax
          bplu7 = bmax
          kbmoi1 = kbmin
          kbmoi2 = kbmin
          kbmoi3 = kbmin
          kbmoi4 = kbmin
          kbmoi5 = kbmin
          kbmoi6 = kbmin
          kbmoi7 = kbmin
          kbplu1 = kbmax
          kbplu2 = kbmax
          kbplu3 = kbmax
          kbplu4 = kbmax
          kbplu5 = kbmax
          kbplu6 = kbmax
          kbplu7 = kbmax
          md34 = 1
          s3 = q(1) - q(2)
          errd = epsq(1) + epsq(2)
          jjbb = 0
          jjdd = 0
          iibb = 0
          iidd = 0
          dmax = AMIN1(SQRT(zco*amax*bmax),dmax)
          amin = AMAX1(amin,(s3-errd-dmax))
          emax = AMIN1(2*SQRT(bmax*cmax),emax)
          cmin = AMAX1(cmin,emin*emin/bmax/2.)
          cmin = AMAX1(cmin,fmin*fmin/amax/zco)
          GOTO 250
        CASE (6)
          irj(1,7) = 1
          amax = q(1)/4. + epsq(1)/4.
          amin = q(1)/4. - epsq(1)/4.
          bmax = q(2) + epsq(2)
          bmin = q(2) - epsq(2)
          kamin = coeff*amin
          kamax = coeff*amax
          kbmin = coeff*bmin
          kbmax = coeff*bmax
          amn = (amin+amax)/2.
          bmn = (bmin+bmax)/2.
          amoi1 = amin
          amoi2 = amin
          amoi3 = amin
          amoi4 = amin
          amoi5 = amin
          amoi6 = amin
          amoi7 = amin
          aplu1 = amax
          aplu2 = amax
          aplu3 = amax
          aplu4 = amax
          aplu5 = amax
          aplu6 = amax
          aplu7 = amax
          bmoi1 = bmin
          bmoi2 = bmin
          bmoi3 = bmin
          bmoi4 = bmin
          bmoi5 = bmin
          bmoi6 = bmin
          bmoi7 = bmin
          bplu1 = bmax
          bplu2 = bmax
          bplu3 = bmax
          bplu4 = bmax
          bplu5 = bmax
          bplu6 = bmax
          bplu7 = bmax
          kamoi1 = kamin
          kamoi2 = kamin
          kamoi3 = kamin
          kamoi4 = kamin
          kamoi5 = kamin
          kamoi6 = kamin
          kamoi7 = kamin
          kaplu1 = kamax
          kaplu2 = kamax
          kaplu3 = kamax
          kaplu4 = kamax
          kaplu5 = kamax
          kaplu6 = kamax
          kaplu7 = kamax
          kbmoi1 = kbmin
          kbmoi2 = kbmin
          kbmoi3 = kbmin
          kbmoi4 = kbmin
          kbmoi5 = kbmin
          kbmoi6 = kbmin
          kbmoi7 = kbmin
          kbplu1 = kbmax
          kbplu2 = kbmax
          kbplu3 = kbmax
          kbplu4 = kbmax
          kbplu5 = kbmax
          kbplu6 = kbmax
          kbplu7 = kbmax
          jjaa = 0
          jjbb = 0
          iiaa = 0
          iibb = 0
          dmax = AMIN1(SQRT(zco*amax*bmax),dmax)
          fmax = AMIN1(SQRT(zco*amax*cmax),fmax)
          cmin = AMAX1(cmin,emin*emin/bmax/2.)
          cmin = AMAX1(cmin,fmin*fmin/amax/zco)
          emax = AMIN1(2*SQRT(bmax*cmax),emax)
          Dmi = dmin
          Dma = dmax
          Cma = cmax
          Cmi = cmin
          Fma = fmax
          Ema = emax
          CALL RELSPE
          IF ( jrd.EQ.0 ) GOTO 250
          jjdd = 0
          GOTO 150
        CASE (7)
          irj(1,7) = 1
          cmin = q(2) - epsq(2)
          cmax = q(2) + epsq(2)
          kcmin = coeff*cmin
          kcmax = coeff*cmax
          cmoi1 = cmin
          cmoi2 = cmin
          cmoi3 = cmin
          cmoi4 = cmin
          cmoi5 = cmin
          cmoi6 = cmin
          cmoi7 = cmin
          cplu1 = cmax
          cplu2 = cmax
          cplu3 = cmax
          cplu4 = cmax
          cplu5 = cmax
          cplu6 = cmax
          cplu7 = cmax
          kcmoi1 = kcmin
          kcmoi2 = kcmin
          kcmoi3 = kcmin
          kcmoi4 = kcmin
          kcmoi5 = kcmin
          kcmoi6 = kcmin
          kcmoi7 = kcmin
          kcplu1 = kcmax
          kcplu2 = kcmax
          kcplu3 = kcmax
          kcplu4 = kcmax
          kcplu5 = kcmax
          kcplu6 = kcmax
          kcplu7 = kcmax
          s5 = q(1)
          errd = epsq(1)
          jjcc = 0
          jjdd = 0
          iicc = 0
          iidd = 0
          md56 = 1
          amax = AMIN1(s5+errd-bmin+dmax,amax)
          bmax = AMIN1(s5+errd-amin+dmax,bmax)
          Amaab = SQRT(4.)*AMAX1(amax,bmax)
          amin = AMAX1(amin,s5-errd-bmax-Amaab)
          bmin = AMAX1(bmin,s5-errd-amax-Amaab)
          dmax = AMIN1(SQRT(zco*amax*bmax),dmax)
          fmax = AMIN1(SQRT(zco*amax*cmax),fmax)
          emax = AMIN1(2*SQRT(bmax*cmax),emax)
          GOTO 250
        CASE (8)
          irj(1,7) = 1
          amin = q(1)/4. - epsq(1)/4.
          amax = q(1)/4. + epsq(1)/4.
          kamin = coeff*amin
          kamax = coeff*amax
          amoi1 = amin
          amoi2 = amin
          amoi3 = amin
          amoi4 = amin
          amoi5 = amin
          amoi6 = amin
          amoi7 = amin
          aplu1 = amax
          aplu2 = amax
          aplu3 = amax
          aplu4 = amax
          aplu5 = amax
          aplu6 = amax
          aplu7 = amax
          kamoi1 = kamin
          kamoi2 = kamin
          kamoi3 = kamin
          kamoi4 = kamin
          kamoi5 = kamin
          kamoi6 = kamin
          kamoi7 = kamin
          kaplu1 = kamax
          kaplu2 = kamax
          kaplu3 = kamax
          kaplu4 = kamax
          kaplu5 = kamax
          kaplu6 = kamax
          kaplu7 = kamax
          s1 = q(2) - q(1)/4.
          errd = epsq(2) + epsq(1)/4.
          jjaa = 0
          jjdd = 0
          iiaa = 0
          iidd = 0
          md12 = 1
          bmin = AMAX1(bmin,(s1-errd-amax-dmax))
          emax = AMIN1(2*SQRT(bmax*cmax),emax)
          dmax = AMIN1(SQRT(zco*amax*bmax),dmax)
          fmax = SQRT(zco*amax*cmax)
          cmin = AMAX1(cmin,emin*emin/bmax/2.)
          cmin = AMAX1(cmin,fmin*fmin/amax/zco)
          GOTO 250
        CASE (9)
          irj(1,7) = 1
          cmin = q(2)/4. - epsq(2)
          cmax = q(2)/4. + epsq(2)
          kcmin = coeff*cmin
          kcmax = coeff*cmax
          cmoi1 = cmin
          cmoi2 = cmin
          cmoi3 = cmin
          cmoi4 = cmin
          cmoi5 = cmin
          cmoi6 = cmin
          cmoi7 = cmin
          cplu1 = cmax
          cplu2 = cmax
          cplu3 = cmax
          cplu4 = cmax
          cplu5 = cmax
          cplu6 = cmax
          cplu7 = cmax
          kcmoi1 = kcmin
          kcmoi2 = kcmin
          kcmoi3 = kcmin
          kcmoi4 = kcmin
          kcmoi5 = kcmin
          kcmoi6 = kcmin
          kcmoi7 = kcmin
          kcplu1 = kcmax
          kcplu2 = kcmax
          kcplu3 = kcmax
          kcplu4 = kcmax
          kcplu5 = kcmax
          kcplu6 = kcmax
          kcplu7 = kcmax
          s5 = q(1)
          errd = epsq(1)
          jjcc = 0
          jjdd = 0
          iicc = 0
          iidd = 0
          md56 = 1
          amax = AMIN1(s5+errd-bmin+dmax,amax)
          bmax = AMIN1(s5+errd-amin+dmax,bmax)
          Amaab = SQRT(4.)*AMAX1(amax,bmax)
          amin = AMAX1(amin,s5-errd-bmax-Amaab)
          bmin = AMAX1(bmin,s5-errd-amax-Amaab)
          dmax = AMIN1(SQRT(zco*amax*bmax),dmax)
          fmax = AMIN1(SQRT(zco*amax*cmax),fmax)
          emax = AMIN1(2*SQRT(bmax*cmax),emax)
          GOTO 250
        CASE (10)
          irj(1,7) = 1
          amin = q(1)/4. - epsq(1)
          amax = q(1)/4. + epsq(1)
          kamin = coeff*amin
          kamax = coeff*amax
          amoi1 = amin
          amoi2 = amin
          amoi3 = amin
          amoi4 = amin
          amoi5 = amin
          amoi6 = amin
          amoi7 = amin
          aplu1 = amax
          aplu2 = amax
          aplu3 = amax
          aplu4 = amax
          aplu5 = amax
          aplu6 = amax
          aplu7 = amax
          kamoi1 = kamin
          kamoi2 = kamin
          kamoi3 = kamin
          kamoi4 = kamin
          kamoi5 = kamin
          kamoi6 = kamin
          kamoi7 = kamin
          kaplu1 = kamax
          kaplu2 = kamax
          kaplu3 = kamax
          kaplu4 = kamax
          kaplu5 = kamax
          kaplu6 = kamax
          kaplu7 = kamax
          s8 = q(2)
          erre = epsq(2)
          jjaa = 0
          jjee = 0
          iiaa = 0
          iiee = 0
          md89 = 1
          Amabc = 2.*(AMAX1(bmax,cmax))
          cmin = AMAX1(s8-bmax-erre-Amabc,cmin)
          bmin = AMAX1(s8-cmax-erre-Amabc,bmin)
          cmax = AMIN1(cmax,s8-bmin+Amabc+erre)
          bmax = AMIN1(bmax,s8-cmin+Amabc+erre)
          dmax = AMIN1(SQRT(zco*amax*bmax),dmax)
          emax = AMIN1(2*SQRT(bmax*cmax),emax)
          fmax = AMIN1(SQRT(zco*amax*cmax),fmax)
          GOTO 250
        CASE (11)
          irj(1,7) = 1
          bmin = q(2)/4. - epsq(2)/4.
          bmax = q(2)/4. + epsq(2)/4.
          kbmin = coeff*bmin
          kbmax = coeff*bmax
          bmoi1 = bmin
          bmoi2 = bmin
          bmoi3 = bmin
          bmoi4 = bmin
          bmoi5 = bmin
          bmoi6 = bmin
          bmoi7 = bmin
          bplu1 = bmax
          bplu2 = bmax
          bplu3 = bmax
          bplu4 = bmax
          bplu5 = bmax
          bplu6 = bmax
          bplu7 = bmax
          kbmoi1 = kbmin
          kbmoi2 = kbmin
          kbmoi3 = kbmin
          kbmoi4 = kbmin
          kbmoi5 = kbmin
          kbmoi6 = kbmin
          kbmoi7 = kbmin
          kbplu1 = kbmax
          kbplu2 = kbmax
          kbplu3 = kbmax
          kbplu4 = kbmax
          kbplu5 = kbmax
          kbplu6 = kbmax
          kbplu7 = kbmax
          s3 = q(1) - q(2)/4.
          errd = epsq(1) + epsq(2)/4.
          jjbb = 0
          jjdd = 0
          iibb = 0
          iidd = 0
          md34 = 1
          dmax = AMIN1(SQRT(zco*amax*bmax),dmax)
          amin = AMAX1(amin,(s3-errd-dmax))
          emax = AMIN1(2*SQRT(bmax*cmax),emax)
          fmax = AMIN1(SQRT(zco*amax*cmax),fmax)
          GOTO 250
        CASE (12)
          s5 = q(1)
          s8 = q(2)
          errd = epsq(1)
          erre = epsq(2)
          md56 = 1
          jjdd = 0
          jjee = 0
          iidd = 0
          md89 = 1
          iiee = 0
          Amabc = 2.*(AMAX1(bmax,cmax))
          cmin = AMAX1(s8-bmax-erre-Amabc,cmin)
          bmin = AMAX1(s8-cmax-erre-Amabc,bmin)
          cmax = AMIN1(cmax,s8-bmin+Amabc+erre)
          bmax = AMIN1(bmax,s8-cmin+Amabc+erre)
          amax = AMIN1(s5+errd-bmin+dmax,amax)
          bmax = AMIN1(s5+errd-amin+dmax,bmax)
          Amaab = SQRT(4.)*AMAX1(amax,bmax)
          amin = AMAX1(amin,s5-errd-bmax-Amaab)
          bmin = AMAX1(bmin,s5-errd-amax-Amaab)
          dmax = AMIN1(SQRT(zco*amax*bmax),dmax)
          fmax = AMIN1(SQRT(zco*amax*cmax),fmax)
          emax = AMIN1(2*SQRT(bmax*cmax),emax)
          GOTO 250
        CASE (13)
          irj(1,7) = 1
          errb = (epsq(1)+epsq(2))/2.
          dmin = (q(2)-q(1))/2. - errb
          dmax = (q(2)-q(1))/2. + errb
          kdmin = coeff*dmin
          kdmax = coeff*dmax
          dmoi1 = dmin
          dmoi2 = dmin
          dmoi3 = dmin
          dmoi4 = dmin
          dmoi5 = dmin
          dmoi6 = dmin
          dmoi7 = dmin
          dplu1 = dmax
          dplu2 = dmax
          dplu3 = dmax
          dplu4 = dmax
          dplu5 = dmax
          dplu6 = dmax
          dplu7 = dmax
          kdmoi1 = kdmin
          kdmoi2 = kdmin
          kdmoi3 = kdmin
          kdmoi4 = kdmin
          kdmoi5 = kdmin
          kdmoi6 = kdmin
          kdmoi7 = kdmin
          kdplu1 = kdmax
          kdplu2 = kdmax
          kdplu3 = kdmax
          kdplu4 = kdmax
          kdplu5 = kdmax
          kdplu6 = kdmax
          kdplu7 = kdmax
          s7 = (q(1)+q(2))/2.
          jjbb = 0
          jjdd = 0
          iibb = 0
          iidd = 0
          amax = AMIN1(amax,s7+errb-bmin)
          bmax = AMIN1(bmax,s7+errb-amin)
          amin = AMAX1(amin,s7-errd-bmax)
          bmin = AMAX1(bmin,s7-errd-amax)
          emax = AMIN1(emax,2.*SQRT(bmax*cmax))
          fmax = AMIN1(SQRT(zco*amax*cmax),fmax)
          md7 = 1
          GOTO 250
        CASE (14)
          irj(1,7) = 1
          amin = q(1)/4. - epsq(1)/4.
          amax = q(1)/4. + epsq(1)/4.
          bmin = q(2)/4. - epsq(2)/4.
          bmax = q(2)/4. + epsq(2)/4.
          amn = (amax+amin)/2.
          bmn = (bmax-bmin)/2.
          jjaa = 0
          jjbb = 0
          iiaa = 0
          iibb = 0
          amoi1 = amin
          amoi2 = amin
          amoi3 = amin
          amoi4 = amin
          amoi5 = amin
          amoi6 = amin
          amoi7 = amin
          aplu1 = amax
          aplu2 = amax
          aplu3 = amax
          aplu4 = amax
          aplu5 = amax
          aplu6 = amax
          aplu7 = amax
          kamoi1 = kamin
          kamoi2 = kamin
          kamoi3 = kamin
          kamoi4 = kamin
          kamoi5 = kamin
          kamoi6 = kamin
          kamoi7 = kamin
          kaplu1 = kamax
          kaplu2 = kamax
          kaplu3 = kamax
          kaplu4 = kamax
          kaplu5 = kamax
          kaplu6 = kamax
          kaplu7 = kamax
          bmoi1 = bmin
          bmoi2 = bmin
          bmoi3 = bmin
          bmoi4 = bmin
          bmoi5 = bmin
          bmoi6 = bmin
          bmoi7 = bmin
          bplu1 = bmax
          bplu2 = bmax
          bplu3 = bmax
          bplu4 = bmax
          bplu5 = bmax
          bplu6 = bmax
          bplu7 = bmax
          kbmoi1 = kbmin
          kbmoi2 = kbmin
          kbmoi3 = kbmin
          kbmoi4 = kbmin
          kbmoi5 = kbmin
          kbmoi6 = kbmin
          kbmoi7 = kbmin
          kbplu1 = kbmax
          kbplu2 = kbmax
          kbplu3 = kbmax
          kbplu4 = kbmax
          kbplu5 = kbmax
          kbplu6 = kbmax
          kbplu7 = kbmax
          dmax = AMIN1(SQRT(zco*amax*bmax),dmax)
          fmax = AMIN1(SQRT(zco*amax*cmax),fmax)
          cmin = AMAX1(cmin,emin*emin/bmax/2.)
          cmin = AMAX1(cmin,fmin*fmin/amax/zco)
          emax = AMIN1(2*SQRT(bmax*cmax),emax)
          Dmi = dmin
          Dma = dmax
          Cma = cmax
          Cmi = cmin
          Fma = fmax
          Ema = emax
          CALL RELSPE
          IF ( jrd.EQ.0 ) GOTO 250
          jjdd = 0
          GOTO 200
        CASE DEFAULT
          irj(1,7) = 1
          amax = q(1) + epsq(1)
          amin = q(1) - epsq(1)
          bmax = q(2) + epsq(2)
          bmin = q(2) - epsq(2)
          kamin = coeff*amin
          kamax = coeff*amax
          kbmin = coeff*bmin
          kbmax = coeff*bmax
          amn = (amin+amax)/2.
          bmn = (bmin+bmax)/2.
          amoi1 = amin
          amoi2 = amin
          amoi3 = amin
          amoi4 = amin
          amoi5 = amin
          amoi6 = amin
          amoi7 = amin
          aplu1 = amax
          aplu2 = amax
          aplu3 = amax
          aplu4 = amax
          aplu5 = amax
          aplu6 = amax
          aplu7 = amax
          bmoi1 = bmin
          bmoi2 = bmin
          bmoi3 = bmin
          bmoi4 = bmin
          bmoi5 = bmin
          bmoi6 = bmin
          bmoi7 = bmin
          bplu1 = bmax
          bplu2 = bmax
          bplu3 = bmax
          bplu4 = bmax
          bplu5 = bmax
          bplu6 = bmax
          bplu7 = bmax
          kamoi1 = kamin
          kamoi2 = kamin
          kamoi3 = kamin
          kamoi4 = kamin
          kamoi5 = kamin
          kamoi6 = kamin
          kamoi7 = kamin
          kaplu1 = kamax
          kaplu2 = kamax
          kaplu3 = kamax
          kaplu4 = kamax
          kaplu5 = kamax
          kaplu6 = kamax
          kaplu7 = kamax
          kbmoi1 = kbmin
          kbmoi2 = kbmin
          kbmoi3 = kbmin
          kbmoi4 = kbmin
          kbmoi5 = kbmin
          kbmoi6 = kbmin
          kbmoi7 = kbmin
          kbplu1 = kbmax
          kbplu2 = kbmax
          kbplu3 = kbmax
          kbplu4 = kbmax
          kbplu5 = kbmax
          kbplu6 = kbmax
          kbplu7 = kbmax
          jjaa = 0
          jjbb = 0
          iiaa = 0
          iibb = 0
          dmax = AMIN1(SQRT(zco*amax*bmax),dmax)
          fmax = AMIN1(SQRT(zco*amax*cmax),fmax)
          cmin = AMAX1(cmin,emin*emin/bmax/2.)
          cmin = AMAX1(cmin,fmin*fmin/amax/zco)
          emax = AMIN1(2*SQRT(bmax*cmax),emax)
          Dmi = dmin
          Dma = dmax
          Cma = cmax
          Cmi = cmin
          Fma = fmax
          Ema = emax
          CALL RELSPE
          IF ( jrd.EQ.0 ) GOTO 250
          jjdd = 0
        END SELECT
 50     dmin = rmin(Jrt)
        dmax = rmax(Jrt)
        dmax = AMIN1(SQRT(zco*amax*bmax),dmax)
        kdmin = coeff*dmin
        kdmax = coeff*dmax
        dmoi1 = dmin
        dmoi2 = dmin
        dmoi3 = dmin
        dmoi4 = dmin
        dmoi5 = dmin
        dmoi6 = dmin
        dmoi7 = dmin
        dplu1 = dmax
        dplu2 = dmax
        dplu3 = dmax
        dplu4 = dmax
        dplu5 = dmax
        dplu6 = dmax
        dplu7 = dmax
        kdmoi1 = kdmin
        kdmoi2 = kdmin
        kdmoi3 = kdmin
        kdmoi4 = kdmin
        kdmoi5 = kdmin
        kdmoi6 = kdmin
        kdmoi7 = kdmin
        kdplu1 = kdmax
        kdplu2 = kdmax
        kdplu3 = kdmax
        kdplu4 = kdmax
        kdplu5 = kdmax
        kdplu6 = kdmax
        kdplu7 = kdmax
        cmax = rcmax(Jrt)
        emax = AMIN1(2*SQRT(bmax*cmax),emax)
        fmax = AMIN1(SQRT(zco*amax*cmax),fmax)
        cmin = AMAX1(cmin,emin*emin/bmax/2.)
        cmin = AMAX1(cmin,fmin*fmin/amax/zco)
        ASSIGN 50 TO Ias
        GOTO 250
 100    dmin = rmin(Jrt)
        dmax = rmax(Jrt)
        dmax = AMIN1(SQRT(zco*amax*bmax),dmax)
        kdmin = coeff*dmin
        kdmax = coeff*dmax
        dmoi1 = dmin
        dmoi2 = dmin
        dmoi3 = dmin
        dmoi4 = dmin
        dmoi5 = dmin
        dmoi6 = dmin
        dmoi7 = dmin
        dplu1 = dmax
        dplu2 = dmax
        dplu3 = dmax
        dplu4 = dmax
        dplu5 = dmax
        dplu6 = dmax
        dplu7 = dmax
        kdmoi1 = kdmin
        kdmoi2 = kdmin
        kdmoi3 = kdmin
        kdmoi4 = kdmin
        kdmoi5 = kdmin
        kdmoi6 = kdmin
        kdmoi7 = kdmin
        kdplu1 = kdmax
        kdplu2 = kdmax
        kdplu3 = kdmax
        kdplu4 = kdmax
        kdplu5 = kdmax
        kdplu6 = kdmax
        kdplu7 = kdmax
        cmax = rcmax(Jrt)
        fmax = AMIN1(SQRT(zco*amax*cmax),fmax)
        cmin = AMAX1(cmin,emin*emin/bmax/2.)
        cmin = AMAX1(cmin,fmin*fmin/amax/zco)
        emax = AMIN1(2*SQRT(bmax*cmax),emax)
        ASSIGN 100 TO Ias
        GOTO 250
 150    dmin = rmin(Jrt)
        dmax = rmax(Jrt)
        dmax = AMIN1(SQRT(zco*amax*bmax),dmax)
        kdmin = coeff*dmin
        kdmax = coeff*dmax
        dmoi1 = dmin
        dmoi2 = dmin
        dmoi3 = dmin
        dmoi4 = dmin
        dmoi5 = dmin
        dmoi6 = dmin
        dmoi7 = dmin
        dplu1 = dmax
        dplu2 = dmax
        dplu3 = dmax
        dplu4 = dmax
        dplu5 = dmax
        dplu6 = dmax
        dplu7 = dmax
        kdmoi1 = kdmin
        kdmoi2 = kdmin
        kdmoi3 = kdmin
        kdmoi4 = kdmin
        kdmoi5 = kdmin
        kdmoi6 = kdmin
        kdmoi7 = kdmin
        kdplu1 = kdmax
        kdplu2 = kdmax
        kdplu3 = kdmax
        kdplu4 = kdmax
        kdplu5 = kdmax
        kdplu6 = kdmax
        kdplu7 = kdmax
        cmax = rcmax(Jrt)
        emax = AMIN1(2*SQRT(bmax*cmax),emax)
        fmax = AMIN1(SQRT(zco*amax*cmax),fmax)
        cmin = AMAX1(cmin,emin*emin/bmax/2.)
        cmin = AMAX1(cmin,fmin*fmin/amax/zco)
        ASSIGN 150 TO Ias
        GOTO 250
 200    dmin = rmin(Jrt)
        dmax = rmax(Jrt)
        dmax = AMIN1(SQRT(zco*amax*bmax),dmax)
        kdmin = coeff*dmin
        kdmax = coeff*dmax
        dmoi1 = dmin
        dmoi2 = dmin
        dmoi3 = dmin
        dmoi4 = dmin
        dmoi5 = dmin
        dmoi6 = dmin
        dmoi7 = dmin
        dplu1 = dmax
        dplu2 = dmax
        dplu3 = dmax
        dplu4 = dmax
        dplu5 = dmax
        dplu6 = dmax
        dplu7 = dmax
        kdmoi1 = kdmin
        kdmoi2 = kdmin
        kdmoi3 = kdmin
        kdmoi4 = kdmin
        kdmoi5 = kdmin
        kdmoi6 = kdmin
        kdmoi7 = kdmin
        kdplu1 = kdmax
        kdplu2 = kdmax
        kdplu3 = kdmax
        kdplu4 = kdmax
        kdplu5 = kdmax
        kdplu6 = kdmax
        kdplu7 = kdmax
        cmax = rcmax(Jrt)
        emax = AMIN1(2*SQRT(bmax*cmax),emax)
        fmax = AMIN1(SQRT(zco*amax*cmax),fmax)
        cmin = AMAX1(cmin,emin*emin/bmax/2.)
        cmin = AMAX1(cmin,fmin*fmin/amax/zco)
        ASSIGN 200 TO Ias
 250    CALL TRICLINI2
        IF (DICVOL_Error .NE. 0) RETURN
        IF ( Jrt.GE.jrd ) THEN
          IF ( jrd.NE.0 ) THEN
            IF ( ndich(8).EQ.0 ) THEN
              cmax = Cma
              dmax = Dma
              dmin = Dmi
              cmin = Cmi
              fmax = Fma
              emax = Ema
              jrd = 0
              jjdd = 1
              iidd = 1
              CALL TRICLINI2
              IF (DICVOL_Error .NE. 0) RETURN
            ENDIF
          ENDIF
          IF ( ndich(8).NE.0 ) GOTO 99999
        ELSE
          Jrt = Jrt + 1
          GOTO Ias
        ENDIF
      ENDDO

99999 END SUBROUTINE TRICLINI1
!
!*****************************************************************************
!
