C
      FUNCTION FFCALC_001(IR)
      INCLUDE 'SGinc\FFCALCTOP.INC'
      INCLUDE 'SGinc\FFCALC_001.INC'
      END
C
      FUNCTION FFCALC_002(IR)
      INCLUDE 'SGinc\FFCALCTOP.INC'
      INCLUDE 'SGinc\FFCALC_002.INC'
      END
C
      FUNCTION FFCALC_039(IR)
      INCLUDE 'SGinc\FFCALCTOP.INC'
      INCLUDE 'SGinc\FFCALC_039.INC'
      END
C
      FUNCTION FFCALC_040(IR)
      INCLUDE 'SGinc\FFCALCTOP.INC'
      INCLUDE 'SGinc\FFCALC_040.INC'
      END
C
      FUNCTION FFCALC_044(IR)
      INCLUDE 'SGinc\FFCALCTOP.INC'
      INCLUDE 'SGinc\FFCALC_044.INC'
      END
C
      FUNCTION FFCALC_050(IR)
      INCLUDE 'SGinc\FFCALCTOP.INC'
      INCLUDE 'SGinc\FFCALC_050.INC'
      END
C
      FUNCTION FFCALC_052(IR)
      INCLUDE 'SGinc\FFCALCTOP.INC'
      INCLUDE 'SGinc\FFCALC_052.INC'
      END
C
      FUNCTION FFCALC_057(IR)
      INCLUDE 'SGinc\FFCALCTOP.INC'
      INCLUDE 'SGinc\FFCALC_057.INC'
      END
C
      FUNCTION FFCALC_058(IR)
      INCLUDE 'SGinc\FFCALCTOP.INC'
      INCLUDE 'SGinc\FFCALC_058.INC'
      END
C
      FUNCTION FFCALC_061(IR)
      INCLUDE 'SGinc\FFCALCTOP.INC'
      INCLUDE 'SGinc\FFCALC_061.INC'
      END
C
      FUNCTION FFCALC_064(IR)
      INCLUDE 'SGinc\FFCALCTOP.INC'
      INCLUDE 'SGinc\FFCALC_064.INC'
      END
C
      FUNCTION FFCALC_065(IR)
      INCLUDE 'SGinc\FFCALCTOP.INC'
      INCLUDE 'SGinc\FFCALC_065.INC'
      END
C
      FUNCTION FFCALC_066(IR)
      INCLUDE 'SGinc\FFCALCTOP.INC'
      INCLUDE 'SGinc\FFCALC_066.INC'
      END
C
      FUNCTION FFCALC_067(IR)
      INCLUDE 'SGinc\FFCALCTOP.INC'
      INCLUDE 'SGinc\FFCALC_067.INC'
      END
C
      FUNCTION FFCALC_069(IR)
      INCLUDE 'SGinc\FFCALCTOP.INC'
      INCLUDE 'SGinc\FFCALC_069.INC'
      END


      FUNCTION FFCALC_112(IR)
      INCLUDE 'SGinc\FFCALCTOP.INC'
      INCLUDE 'SGinc\FFCALC_112.INC'
      END
C
      FUNCTION FFCALC_115(IR)
      INCLUDE 'SGinc\FFCALCTOP.INC'
      INCLUDE 'SGinc\FFCALC_115.INC'
      END
C
      FUNCTION FFCALC_116(IR)
      INCLUDE 'SGinc\FFCALCTOP.INC'
      INCLUDE 'SGinc\FFCALC_116.INC'
      END
C
      FUNCTION FFCALC_143(IR)
      INCLUDE 'SGinc\FFCALCTOP.INC'
      INCLUDE 'SGinc\FFCALC_143.INC'
      END
C
      FUNCTION FFCALC_164(IR)
      INCLUDE 'SGinc\FFCALCTOP.INC'
      INCLUDE 'SGinc\FFCALC_164.INC'
      END
C
      FUNCTION FFCALC_176(IR)
      INCLUDE 'SGinc\FFCALCTOP.INC'
      INCLUDE 'SGinc\FFCALC_176.INC'
      END
C
      FUNCTION FFCALC_212(IR)
      INCLUDE 'SGinc\FFCALCTOP.INC'
      INCLUDE 'SGinc\FFCALC_212.INC'
      END
C
      FUNCTION FFCALC_266(IR)
      INCLUDE 'SGinc\FFCALCTOP.INC'
      INCLUDE 'SGinc\FFCALC_266.INC'
      END
C
      FUNCTION FFCALC_269(IR)
      INCLUDE 'SGinc\FFCALCTOP.INC'
      INCLUDE 'SGinc\FFCALC_269.INC'
      END
C
      FUNCTION FFCALC_284(IR)
      INCLUDE 'SGinc\FFCALCTOP.INC'
      INCLUDE 'SGinc\FFCALC_284.INC'
      END
C
      FUNCTION FFCALC_290(IR)
      INCLUDE 'SGinc\FFCALCTOP.INC'
      INCLUDE 'SGinc\FFCALC_290.INC'
      END
C
      FUNCTION FFCALC_292(IR)
      INCLUDE 'SGinc\FFCALCTOP.INC'
      INCLUDE 'SGinc\FFCALC_292.INC'
      END
C
      FUNCTION FFCALC_298(IR)
      INCLUDE 'SGinc\FFCALCTOP.INC'
      INCLUDE 'SGinc\FFCALC_298.INC'
      END
C
      FUNCTION FFCALC_304(IR)
      INCLUDE 'SGinc\FFCALCTOP.INC'
      INCLUDE 'SGinc\FFCALC_304.INC'
      END
C
      FUNCTION FFCALC_356(IR)
      INCLUDE 'SGinc\FFCALCTOP.INC'
      INCLUDE 'SGinc\FFCALC_356.INC'
      END
C
      FUNCTION FFCALC_365(IR)
      INCLUDE 'SGinc\FFCALCTOP.INC'
      INCLUDE 'SGinc\FFCALC_365.INC'
      END
C
      FUNCTION FFCALC_369(IR)
      INCLUDE 'SGinc\FFCALCTOP.INC'
      INCLUDE 'SGinc\FFCALC_369.INC'
      END
C
      FUNCTION FFCALC_430(IR)
      INCLUDE 'SGinc\FFCALCTOP.INC'
      INCLUDE 'SGinc\FFCALC_430.INC'
      END
C
      FUNCTION FFCALC_431(IR)
      INCLUDE 'SGinc\FFCALCTOP.INC'
      INCLUDE 'SGinc\FFCALC_431.INC'
      END
C
      FUNCTION FFCALC_432(IR)
      INCLUDE 'SGinc\FFCALCTOP.INC'
      INCLUDE 'SGinc\FFCALC_432.INC'
      END
C
      FUNCTION FFCALC_433(IR)
      INCLUDE 'SGinc\FFCALCTOP.INC'
      INCLUDE 'SGinc\FFCALC_433.INC'
      END
C
      FUNCTION FFCALC_434(IR)
      INCLUDE 'SGinc\FFCALCTOP.INC'
      INCLUDE 'SGinc\FFCALC_434.INC'
      END 
C
      FUNCTION FFCALC_435(IR)
      INCLUDE 'SGinc\FFCALCTOP.INC'
      INCLUDE 'SGinc\FFCALC_435.INC'
      END

	FUNCTION FFCALC_449(IR)
      INCLUDE 'SGinc\FFCALCTOP.INC'
      INCLUDE 'SGinc\FFCALC_449.INC'
      END

	FUNCTION FFCALC_451(IR)
      INCLUDE 'SGinc\FFCALCTOP.INC'
      INCLUDE 'SGinc\FFCALC_451.INC'
      END


	FUNCTION FFCALC_462(IR)
      INCLUDE 'SGinc\FFCALCTOP.INC'
      INCLUDE 'SGinc\FFCALC_462.INC'
      END

	FUNCTION FFCALC_468(IR)
      INCLUDE 'SGinc\FFCALCTOP.INC'
      INCLUDE 'SGinc\FFCALC_468.INC'
      END

	FUNCTION FFCALC_469(IR)
      INCLUDE 'SGinc\FFCALCTOP.INC'
      INCLUDE 'SGinc\FFCALC_469.INC'
      END

	FUNCTION FFCALC_471(IR)
      INCLUDE 'SGinc\FFCALCTOP.INC'
      INCLUDE 'SGinc\FFCALC_471.INC'
      END

	FUNCTION FFCALC_481(IR)
      INCLUDE 'SGinc\FFCALCTOP.INC'
      INCLUDE 'SGinc\FFCALC_481.INC'
      END

	FUNCTION FFCALC_483(IR)
      INCLUDE 'SGinc\FFCALCTOP.INC'
      INCLUDE 'SGinc\FFCALC_483.INC'
      END

	FUNCTION FFCALC_485(IR)
      INCLUDE 'SGinc\FFCALCTOP.INC'
      INCLUDE 'SGinc\FFCALC_485.INC'
      END
C
C
      FUNCTION FFCALC_DEFAULT(IR)
C
      COMPLEX SUM1,TERM,CFCALC
      DIMENSION RH(3),H(3)
      INCLUDE 'SGinc\FFCALCTOP.INC'
      COMMON /CONSTA/PI,RAD,DEG,TWOPI,FOURPI,PIBY2,ALOG2,SQL2X8,VALMUB
      COMMON /NSYM/NOP,NCENT,NOPC,NLAT,NGEN,CENTRC,KOM13
      LOGICAL CENTRC
      COMMON /SYMDA/SYM(3,3,24),TRANS(3,24),ALAT(3,4),
     & ORIGIN(3),KOM26
	common /symsto/sctrh(24,10000),rhsto(3,24,10000)
	PARAMETER (NAC=256,NBC=100*NAC,FARCOS=256.)
	COMMON /COSARS/ COSAR0(-NBC:NBC),COSAR1(-NBC:NBC),COSAR2(-NBC:NBC)
	COMMON /SINARS/ SINAR0(-NBC:NBC),SINAR1(-NBC:NBC),SINAR2(-NBC:NBC)
C
C
      AFCALC=0.
C
C.. Firstly if we are centric then calculate only cosine terms
C
	IF (CENTRC) THEN
       IF (LOG_HYDROGENS) THEN
        DO N = 1,NATOM
         SUM = 0.
C SUM OVER SYMMETRY EQUIVALENTS:
         DO I = 1,NOPC
C.. V is 2pi*(h*x+t)
	     V=(X(1,N)*RHSTO(1,I,IR)+X(2,N)*RHSTO(2,I,IR)+
     &        X(3,N)*RHSTO(3,I,IR)+SCTRH(I,IR))*FARCOS
            IV=V
            PV=V-FLOAT(IV)
            SUM=SUM + COSAR0(IV)+PV*(COSAR1(IV)+PV*COSAR2(IV))
	   END DO
         AFCALC=AFCALC+SUM*FOB(N,IR)
        END DO
       ELSE
        DO NS = 1,NSATOM
         N=ISATOM(NS)
         SUM = 0.
C
C SUM OVER SYMMETRY EQUIVALENTS:
         DO I = 1,NOPC
	     V=(X(1,N)*RHSTO(1,I,IR)+X(2,N)*RHSTO(2,I,IR)+
     &      X(3,N)*RHSTO(3,I,IR)+SCTRH(I,IR))*FARCOS
            IV=V
            PV=V-FLOAT(IV)
            SUM=SUM + COSAR0(IV)+PV*(COSAR1(IV)+PV*COSAR2(IV))
	   END DO
         AFCALC=AFCALC+SUM*FOB(N,IR)
        END DO
       END IF
       FFCALC_DEFAULT=AFCALC*AFCALC
	ELSE
C.. Deal with the non-centric case
	 BFCALC=0.
       IF (LOG_HYDROGENS) THEN
        DO N = 1,NATOM
          SUMA = 0.
	   SUMB = 0.
C
C SUM OVER SYMMETRY EQUIVALENTS:
          DO I = 1,NOPC
C.. V is 2pi*(h*x+t)
	     V=(X(1,N)*RHSTO(1,I,IR)+X(2,N)*RHSTO(2,I,IR)+
     &        X(3,N)*RHSTO(3,I,IR)+SCTRH(I,IR))*FARCOS
            IV=V
            PV=V-FLOAT(IV)
            SUMA=SUMA + COSAR0(IV)+PV*(COSAR1(IV)+PV*COSAR2(IV))
            SUMB=SUMB + SINAR0(IV)+PV*(SINAR1(IV)+PV*SINAR2(IV))
	   END DO
          AFCALC=AFCALC+SUMA*FOB(N,IR)
          BFCALC=BFCALC+SUMB*FOB(N,IR)
        END DO
       ELSE
        DO NS = 1,NSATOM
          N=ISATOM(NS)
          SUMA = 0.
	   SUMB = 0.
C
C SUM OVER SYMMETRY EQUIVALENTS:
          DO I = 1,NOPC
	     V=(X(1,N)*RHSTO(1,I,IR)+X(2,N)*RHSTO(2,I,IR)+
     &        X(3,N)*RHSTO(3,I,IR)+SCTRH(I,IR))*FARCOS
            IV=V
            PV=V-FLOAT(IV)
            SUMA=SUMA + COSAR0(IV)+PV*(COSAR1(IV)+PV*COSAR2(IV))
            SUMB=SUMB + SINAR0(IV)+PV*(SINAR1(IV)+PV*SINAR2(IV))
	   END DO
          AFCALC=AFCALC+SUMA*FOB(N,IR)
          BFCALC=BFCALC+SUMB*FOB(N,IR)
        END DO
       END IF
       FFCALC_DEFAULT=AFCALC*AFCALC+BFCALC*BFCALC
	END IF
      RETURN
      END
C
	SUBROUTINE CALCOSARX
	PARAMETER (NAC=256,NBC=100*NAC,FARCOS=256.)
	COMMON /COSARS/ COSAR0(-NBC:NBC),COSAR1(-NBC:NBC),COSAR2(-NBC:NBC)
	COMMON /SINARS/ SINAR0(-NBC:NBC),SINAR1(-NBC:NBC),SINAR2(-NBC:NBC)
C
	TWOPI=8.*ATAN(1.)
	AMUL=TWOPI/FARCOS
	DO I=-NBC,NBC
	  X =AMUL*FLOAT(I)
	  XP=AMUL*FLOAT(I+1)
	  XM=AMUL*FLOAT(I-1)
	  COSAR0(I)=COS(X)
	  COSAR1(I)=0.5*(COS(XP)-COS(XM))
	  COSAR2(I)=0.5*(COS(XP)+COS(XM)-2.*COSAR0(I))
	  SINAR0(I)=SIN(X)
	  SINAR1(I)=0.5*(SIN(XP)-SIN(XM))
	  SINAR2(I)=0.5*(SIN(XP)+SIN(XM)-2.*SINAR0(I))
	END DO
C
	END
