      SUBROUTINE INF_UPLOAD()
!
  USE WINTERACTER
  USE DRUID_HEADER
!

      INCLUDE 'PARAMS.INC'

      COMMON /FCSTOR/MAXK,FOB(150,MFCSTO)
      LOGICAL LOGREF
      COMMON /FCSPEC/ NLGREF,IREFH(3,MFCSPE),LOGREF(8,MFCSPE)
      COMMON /POSNS/NATOM,X(3,150),KX(3,150),AMULT(150), &
      TF(150),KTF(150),SITE(150),KSITE(150), &
      ISGEN(3,150),SDX(3,150),SDTF(150),SDSITE(150),KOM17
      COMMON /SAREFLNS/AIOBS(MSAREF),AICALC(MSAREF)
      COMMON /CHISTO/ KKOR,WTIJ(MCHIHS),S2S(MCHIHS),S4S(MCHIHS),&
      IKKOR(MCHIHS),JKKOR(MCHIHS)
!
      LOGICAL IHMINLT0,IKMINLT0,ILMINLT0
      COMMON /CSQLOG/ IHMINLT0,IKMINLT0,ILMINLT0
      COMMON /CSQINT/ IHMIN,IHMAX,IKMIN,IKMAX,ILMIN,ILMAX,IIMIN,IIMAX
      COMMON /FPINF2/ NTERMS
!
      CALL WDialogSelect(IDD_input_data)
      CALL WDialogPutInteger(IDF_reflections,maxk)
      CALL WDialogPutInteger(IDF_contributors,nterms)
      CALL WDialogPutInteger(IDF_correlations,kkor)
      CALL WDialogPutInteger(IDF_numatoms,natom)
!
      END