      FUNCTION MULTIPEAK_CHISQ(NPAR,P)
      REAL MULTIPEAK_CHISQ
C

	INCLUDE 'PARAMS.INC'

      PARAMETER (NW=4)
      DIMENSION C3FN(3)
      COMMON /WWCARDRC/ICRYDA,NTOTAL(9),NYZ,NTOTL,INREA(26,9),
     & ICDN(26,9),IERR,IO10,SDREAD
      LOGICAL SDREAD
      DIMENSION INREAD(26),ICDNO(26)
      EQUIVALENCE (INREAD(1),INREA(1,1))
      EQUIVALENCE (ICDNO(1),ICDN(1,1))
      COMMON /CONSTA/PI,RAD,DEG,TWOPI,FOURPI,PIBY2,ALOG2,SQL2X8,VALMUB

      COMMON /WWF4PARS/NGEN4(9,5),F4VAL(3,MF4PAR),
     & F4PAR(3,MF4PAR),KF4PAR(3,MF4PAR),F4PESD(3,MF4PAR),KOM6

      COMMON /WWIOUNIT/LPT,ITI,ITO,IPLO,LUNI,IOUT
      COMMON /WWNEWOLD/SHIFT,XOLD,XNEW,ESD,IFAM,IGEN,ISPC,
     & NEWIN,KPACK,LKH,SHESD,ISHFT,AVSHFT,AMAXSH
      COMMON /WWPAWLPR/AKLO,AKHI,SLACK,STRKT,STRTOL,SLKTOL,ITST,
     & ISPSLK(2,1000),IGSLAK(1000),AMSLAK(2,1000),WTSLAK(1000),
     & WEELEV,KOM16
      LOGICAL STRKT
      COMMON /WWPHASE/NPHASE,IPHASE,JPHASE,KPHASE,NPHUNI(9),
     & SCALEP(9),KSCALP(9),PHMAG(9)
      LOGICAL PHMAG
      COMMON /WWPRBLEM/NFAM,NGENPS(6,9),NSPCPS(6,9),
     & LF1SP(5),LF3SP(10,9,5),LVFST1(6,9,5),
     & LBFST1(6,9,5),NVARF(6,9,5),
     & NBARF(6,9,5),LF6SP(3,5)
      DIMENSION NGENS(6),NSPC(6)
      EQUIVALENCE (NGENS(1),NGENPS(1,1)),(NSPC(1),NSPCPS(1,1))

      COMMON /WWPRPKCN/ARGK,PKCNSP(6,9,5),
     & KPCNSP(6,9,5),DTDPCN(6),DTDWL,
     & NPKCSP(9,5),ARGMIN(5),ARGMAX(5),
     & ARGSTP(5),PCON

      COMMON /WWPRPKFN/ARGI,YNORM,PKFNSP(8,6,9,5),
     & KPFNSP(8,6,9,5),
     & DERPFN(8,6),NPKFSP(8,9,5),TOLER(8,9,
     & 5),NPKGEN(9,5),PKFNVA(8),DYNDVQ(8),
     & DYNDKQ,REFUSE,CYC1,NOPKRF,TOLR(2,5),NFFT,AKNOTS,
     & NBASF4(MPRPKF,2,9),L4END(9),L6ST,L6END

      LOGICAL REFUSE,CYC1,NOPKRF
      COMMON /WWPRSAVZ/PKCONV(2048,9)
      COMMON /WWPWORDS/PWD(10,9,5)
      CHARACTER *4 PWD

      COMMON /WWREFLNS/REFH(3,WWREFDIM),AMUL(WWREFDIM),AICALC(WWREFDIM),
     & AIOBS(WWREFDIM),ESDOBS(WWREFDIM),SOMEGA(WWREFDIM),GGCALC(300),
     & MAXKK(9),KMIN,KMAX,KMOD,KNOW,DSTAR(WWREFDIM),ISMAG(WWREFDIM),
     & DKDDS,KOM23

      EQUIVALENCE (MAXK,MAXKK(1))
      COMMON /WWSOURCE/NSOURC,JSOURC,KSOURC,NDASOU(5),METHOD(
     & 9),NPFSOU(9,5),NSOBS(5),SCALES(5),
     & KSCALS(5),NPCSOU(9,5)
C
C.. Note only 3 phases specifically hardwired here
      COMMON /WWREFLNZ/ZARGK(MRFLNZ),ZXDEL(MRFLNZ)

      COMMON /ZSTORE/ NPTS,ZARGI(MPPTS),ZOBS(MPPTS),ZDOBS(MPPTS),
     &ZWT(MPPTS),ICODEZ(MPPTS),KOBZ(MPPTS)
      COMMON /YSTORE/ ZCAL(MPPTS),ZBAK(MPPTS)
      COMMON /ZSTOR1/ ZXDELT,IIMIN,IIMAX,XDIFT,XMINT
      COMMON /ZSTOR2/ MN,MN2
C
C
      COMMON /WWCMN299/KIPT(MPTS),KNIPT(MAXPIK),ZNORM(MAXPIK),
     &DZNDKQ(MAXPIK),DZNDVQ(9,MAXPIK),IOCCR(MPTS),JOCCR(MPTS)!,

      COMMON /WWCMN300/ZNORMT(MAXPIK),DZNDKQT(MAXPIK),DZNDVQT(9,MAXPIK),
     &KARGO(MAXPIK),KARGK(MAXPIK)
C
      PARAMETER (MPAR=50)
      REAL P(MPAR)
      PARAMETER (MPT=2000)
      COMMON /LSQDAT/ NPT,X(MPT),Y(MPT),E(MPT)
      PARAMETER (MPeak=10)
      COMMON /MULTPK/NPEAK,AREA(MPEAK),XPOS(MPEAK),IPOS(MPEAK)
C
      LOGICAL  LERANL
      COMMON   /PKCOM3/ LERANL
C.. Profile refinement stage:
C.. Single peak-fitting code
C
C
      DO I=1,NPEAK
        KK=4+2*I
        AREA(I)=P(KK+1)
        ZARGK(I)=P(KK+2)
      END DO
      DO IV=1,NPKGEN(1,1)!JPHASE,JSOURC)
        IVV=IV+2
        PKFNVA(IV)=P(IVV)
      END DO
C
C.. FFT CALCULATION STAGE IN PROFILE REFINEMENT
C.. THE INDIVIDUAL COMPONENTS FOR CONVOLUTION ARE IMMEDIATELY
C.. DESCRIBED IN FOURIER SPACE (GETS RID OF DISCONTINUITY PROBLEMS)
      NPEAK2=1+NPEAK/2
      ARGK=ZARGK(NPEAK2)
      CALL PF_FCSUB3(MN)
C
C.. FFT OVER
C.. FIND THE PEAK MAXIMUM VALUE AND THEN WORK OUT THE PEAK LIMITS
      CCHI=0.
      DO II=IIMIN,IIMAX
        TARGI=ZARGI(II)
        YBACK=P(1)+P(2)*(TARGI-XMINT)!/XDIFT
        ZBAK(II)=YBACK
        ZCAL(II)=YBACK
        DO JJ=1,NPEAK
          ARGK=ZARGK(JJ)
          DTARG=TARGI-ARGK
C
C... DO THE INTERPOLATIONS FOR YNORM AND DERIVATIVES FROM PKLIST
          JARGI=NINT(DTARG/ZXDELT)
          IARGI=JARGI+MN2+1
C.. WORK OUT ARGI OFFSET FROM "X(JARGI)" FOR INTERPOLATION
          POFF= DTARG/ZXDELT - FLOAT(JARGI)
C.. WORK OUT INTERPOLATION COEFFICIENTS FOR FUNCTIONS
          C3FN(1)= 0.5*POFF*(POFF-1.)
          C3FN(2)= 1.-POFF**2
          C3FN(3)= 0.5*POFF*(POFF+1.)
C
          YNORM=0.
          DO I=1,3
            III=IARGI+I-2
            PKTEM=PKCONV(III,1)
            YNORM=YNORM+C3FN(I)*PKTEM
          END DO
C
          YCALC=AREA(JJ)*YNORM+YBACK
          ZCAL(II)=ZCAL(II)+YCALC
        END DO
        CHIADD=(ZOBS(II)-ZCAL(II))/ZDOBS(II)
        CCHI=CCHI+CHIADD*CHIADD
      END DO !  II LOOP
C
C.. Penalise against any negative peak widths
      IF (.NOT.LERANL) THEN
        DO IV=1,NPKGEN(1,1)
          PTEM=100.*PKFNVA(IV)
          IF (PTEM.LT.0.) CCHI=CCHI+PTEM*PTEM
        END DO
      END IF
C
C
      MULTIPEAK_CHISQ=CCHI
C
      END
C
C
C
C
C
C LEVEL 1      SUBROUTINE PF_FCSUB3(MNS)
      SUBROUTINE PF_FCSUB3(MNS)
C
C
CX   For use with PFCN03 constant wavelength data with finite detector height
CC 19B
CH

	INCLUDE 'PARAMS.INC'

      LOGICAL NEAR90
      COMPLEX CFFT,CFF
      COMMON /CONSTA/PI,RAD,DEG,TWOPI,FOURPI,PIBY2,ALOG2,SQL2X8,VALMUB
      COMMON /WWPHASE/NPHASE,IPHASE,JPHASE,KPHASE,NPHUNI(9),
     & SCALEP(9),KSCALP(9),PHMAG(9)
      LOGICAL PHMAG
      COMMON /WWPRPKCN/ARGK,PKCNSP(6,9,5),
     & KPCNSP(6,9,5),DTDPCN(6),DTDWL,
     & NPKCSP(9,5),ARGMIN(5),ARGMAX(5),
     & ARGSTP(5),PCON
      COMMON /WWPRPKFN/ARGI,YNORM,PKFNSP(8,6,9,5),
     & KPFNSP(8,6,9,5),
     & DERPFN(8,6),NPKFSP(8,9,5),TOLER(8,9,
     & 5),NPKGEN(9,5),PKFNVA(8),DYNDVQ(8),
     & DYNDKQ,REFUSE,CYC1,NOPKRF,TOLR(2,5),NFFT,AKNOTS,
     & NBASF4(MPRPKF,2,9),L4END(9),L6ST,L6END
      LOGICAL REFUSE,CYC1,NOPKRF
      COMMON /WWPRSAVZ/PKCONV(2048,9)
C      COMMON /WWPRSAVF/PKLIST(2048,9,200),ZXDEL(200),PKCONV(2048,9),
C     & ARGNOT(50),PKNOT(64,9,50),XPDKNT(50)

      COMMON /WWREFLNZ/ZARGK(MRFLNZ),ZXDEL(MRFLNZ)

      COMMON /WWREFLNS/REFH(3,WWREFDIM),AMUL(WWREFDIM),AICALC(WWREFDIM),
     & AIOBS(WWREFDIM),ESDOBS(WWREFDIM),SOMEGA(WWREFDIM),GGCALC(300),
     & MAXKK(9),KMIN,KMAX,KMOD,KNOW,DSTAR(WWREFDIM),ISMAG(WWREFDIM),
     & DKDDS,KOM23
      EQUIVALENCE (MAXK,MAXKK(1))
      COMMON /WWSOURCE/NSOURC,JSOURC,KSOURC,NDASOU(5),METHOD(
     & 9),NPFSOU(9,5),NSOBS(5),SCALES(5),
     & KSCALS(5),NPCSOU(9,5)
      DIMENSION CFFT(8),
     1FR(2048,8),FI(2048,8),
     2FRT(2048),FIT(2048)
C
      LOGICAL  LERANL
      COMMON   /PKCOM3/ LERANL
C
      IF (LERANL) THEN
        SIG= ABS(PKFNVA(1))
        GAM= ABS(PKFNVA(2))
        HPS= ABS(PKFNVA(3))
        HMS= ABS(PKFNVA(4))
      ELSE
        SIG= PKFNVA(1)
        GAM= PKFNVA(2)
        HPS= PKFNVA(3)
        HMS= PKFNVA(4)
      END IF
C
C
      DENTEM=(FLOAT(MNS)*ZXDEL(KNOW))
      C2TEM= PI/DENTEM
      CTEM=  2.*C2TEM
      GTEM=  CTEM*SIG
      CLTEM= C2TEM*GAM
C      WRITE(*,*) 'F',DENTEM,C2TEM,CTEM,GTEM,CLTEM,PI,ZXDEL(KNOW),ARGK
C      WRITE(*,*) 'F',(PKFNVA(II),II=1,4)
C.. TO DEAL WITH (A) 90 DEGREES AND (B) ABOVE ALL WE WILL DO IS
C.. (A) SET FR(I,3)=1 AND ALL ELSE TO ZERO AND
C.. (B) SWITCH THE SIGN OF THE IMAGINARY COMPONENTS
      NEAR90=(ABS(ARGK-90.).LT.2.0)
      IF(.NOT.NEAR90) THEN
        TANRA= ABS(TAN(RAD*ARGK))
        DENASY=0.5*(HPS-HMS)*(HPS+HMS)
C.. BET1 AND NETPI CHANGE SIGN AT 90 DEGREES
C.. BET2, BETP, BETM, BETP2 AND BETM2 DO NOT
        BET1=0.5*RAD*DENTEM*TANRA
        BET2=SQRT(BET1)
        BETP=HPS/BET2
        BETM=HMS/BET2
        BETP2=PIBY2*BETP*BETP
        BETM2=PIBY2*BETM*BETM
        BETPI=BET1/PI
      END IF
C
      MN2=MNS/2
      MN2M1= MN2-1
      MN2P1= MN2+1
      DO 1 I=1,MNS
        II=MOD(I+MN2,MNS)-MN2P1
C.. GAUSSIAN
        ARG= GTEM*FLOAT(II)
        FR(I,1)= EXP(-0.5*ARG*ARG)
        FI(I,1)= 0.
C!!        DR(I,1)= -ARG*ARG*FR(I,1)/SIG
C!!        DI(I,1)= 0.
C.. LORENTZIAN
        AFII= ABS(FLOAT(II))
        ARG= MAX(0.,CLTEM*AFII)
        FR(I,2)= EXP(-ARG)
        FI(I,2)= 0.
C!!        DR(I,2)= -C2TEM*AFII*FR(I,2)
C!!        DI(I,2)= 0.
C.. ASYMMETRY FUNCTION FOR UMBRELLA EFFECT
	IF (II.EQ.0.OR.NEAR90) THEN
          FR(I,3)=1.
          FI(I,3)=0.
C!!          DR(I,3)=0.
C!!          DR(I,4)=0.
C!!          DI(I,3)=0.
C!!          DI(I,4)=0.
	ELSE
          SII=SQRT(AFII)
          VAL=FLOAT(II)
          SVAL=SII/VAL
          ARGP1= BETP*SII
          ARGM1= BETM*SII
          CALL PF_FRENEL(ARGP1,FRCP,FRSP)
          CALL PF_FRENEL(ARGM1,FRCM,FRSM)
          FRCP=FRCP*BET2/SII
          FRSP=FRSP*BET2*SVAL
          FRCM=FRCM*BET2/SII
          FRSM=FRSM*BET2*SVAL
          BETPK=BETPI/VAL
          SINP=SIN(BETP2*VAL)
          SINM=SIN(BETM2*VAL)
          COSP=COS(BETP2*VAL)
          COSM=COS(BETM2*VAL)
C.. BET1 AND BETPI CHANGE SIGN AT 90 DEGREES
C.. BET2, BETP, BETM, BETP2 AND BETM2 DO NOT
C
          FR(I,3)=((HPS*FRCP-HMS*FRCM)-BETPK*(SINP-SINM))/DENASY
          FI(I,3)=-((HPS*FRSP-HMS*FRSM)+BETPK*(COSP-COSM))/DENASY
C!!          DR(I,3)= (FRCP-HPS*FR(I,3))/DENASY
C!!          DI(I,3)= -(FRSP-HPS*FI(I,3))/DENASY
C!!          DR(I,4)= (HMS*FR(I,3)-FRCM)/DENASY
C!!          DI(I,4)= -(HMS*FI(I,3)-FRSM)/DENASY
          IF (ARGK.GT.90.) THEN
            FI(I,3)=-FI(I,3)
C!!            DI(I,3)=-DI(I,3)
C!!            DI(I,4)=-DI(I,4)
          END IF
	END IF
   1  CONTINUE
C
C.. NOW FORM PRODUCTS IN FOURIER SPACE
      DO 2 I=1,MNS       
       DO 3 J=1,3!NPKGEN(JPHASE,JSOURC)
         CFFT(J)=CMPLX(FR(I,J),FI(I,J))
C!!        IF(J.NE.4) CFFT(J)=CMPLX(FR(I,J),FI(I,J))
C!!        DFFT(J)=CMPLX(DR(I,J),DI(I,J))
   3   CONTINUE
C!!        DDT(1)=DFFT(1)*CFFT(2)*CFFT(3)
C!!        DDT(2)=DFFT(2)*CFFT(1)*CFFT(3)
C!!        DDT(3)=DFFT(3)*CFFT(1)*CFFT(2)
C!!        DDT(4)=DFFT(4)*CFFT(1)*CFFT(2)
C!!        DO 4 J=1,NPKGEN(JPHASE,JSOURC)
C!!         DR(I,J)=REAL(DDT(J))
C!!         DI(I,J)=AIMAG(DDT(J))
C!!   4  CONTINUE
        CFF=CFFT(1)*CFFT(2)*CFFT(3)
        FRT(I)=REAL(CFF)
        FIT(I)=AIMAG(CFF)
   2  CONTINUE
C
C.. DO INVERSE TRANSFORMS OF FUNCTION AND DERIVATIVES
      INV=1
      CALL WWFT01A(MNS,INV,FRT,FIT)
C
C!!      DO 5 J=1,NPKGEN(JPHASE,JSOURC)
C!!   5   CALL WWFT01A(MNS,INV,DR(1,J),DI(1,J))
C.. WRITE FUNCTION AND DERIVATIVES TO ARRAY PKADD
      XTEM=1./ZXDEL(KNOW)
      DO 6 I=1,MNS
      II=MOD(I+MN2M1,MNS)+1
      PKCONV(II,1)=FRT(I)*XTEM
C!!      DO 7 J=1,NPKGEN(JPHASE,JSOURC)
C!!      JJ=J+1
C!!      PKCONV(II,JJ)=DR(I,J)*XTEM
C!!   7  CONTINUE
   6  CONTINUE
C
      RETURN
      END       
C
C
C
C
C LEVEL 1      SUBROUTINE PF_FRENEL(Z,FRCOS,FRSIN)
      SUBROUTINE PF_FRENEL(Z,FRCOS,FRSIN)
C
C *** PF_FRENEL by WIFD 23 Feb 93 ***
C
CX
CC 9C
CH Calculates ?
CA On entry Z holds the argument
CA On exit FRCOS, FRSIN hold ?
C
      COMMON /CONSTA/PI,RAD,DEG,TWOPI,FOURPI,PIBY2,ALOG2,SQL2X8,VALMUB
C
      FZ= (1.+Z*0.926)/(2.+Z*(1.792+Z*3.104))
      GZ= 1./(2.+Z*(4.142+Z*(3.492+Z*6.670)))
C
      ARG=PIBY2*Z*Z
      SINARG=SIN(ARG)
      COSARG=COS(ARG)
      FRCOS=0.5+FZ*SINARG-GZ*COSARG
      FRSIN=0.5-FZ*COSARG-GZ*SINARG
C
      RETURN
      END
C
