//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by PCDruid_resource.RC
//
#define IDD_Structural_Information      101
#define IDD_About_Polyfitter            102
#define IDD_Plot_Option_Dialog          103
#define IDD_Peak_Positions              104
#define IDD_Data_Properties             105
#define IDD_Peak_Widths                 106
#define IDD_Crystal_Symmetry            107
#define IDD_TEMPLATE01                  108
#define IDD_Sigma_info                  109
#define IDD_Gamma_Info                  110
#define IDD_TEMPLATE02                  111
#define IDD_HPSL_info                   112
#define IDF_Width_Equations             113
#define IDD_DIALOG1                     113
#define IDD_HMSL_Info                   114
#define IDD_Width_Equations             115
#define IDD_TEMPLATE04                  116
#define IDD_TEMPLATE03                  117
#define IDD_TEMPLATE05                  118
#define IDD_SA_input1                   119
#define IDD_SA_input2                   120
#define IDD_Polyfitter_Wizard_01        121
#define IDD_PW_Page1                    122
#define IDD_PW_Page2                    123
#define IDD_PW_Page3                    124
#define IDD_Pawley_Status               125
#define IDD_SA_Action2                  126
#define IDD_HELP                        127
#define IDD_strsol_input                128
#define IDD_control_file                129
#define IDD_space_group                 130
#define IDD_input_protocol              131
#define IDD_DIALOG001                   132
#define IDD_input_data                  133
#define IDD_zmatrix_files               134
#define IDD_DIALOG002                   135
#define IDD_Parameter_Status            136
#define IDD_DIALOG003                   137
#define IDD_Anneal_Status               138
#define IDD_Profile_Status              139
#define IDD_input_parameters            140
#define IDD_TEMPLATE009                 141
#define IDD_SA_input3                   142
#define IDD_SA_Action1                  143
#define IDD_zmatrix_tabpane             144
#define ID_Zmatrix_mol1                 145
#define ID_Zmatrix_mol2                 146
#define ID_Zmatrix_mol3                 147
#define ID_Zmtarix_mol4                 148
#define ID_Zmatrix_mol5                 149
#define ID_About_PolyFitter             1001
#define IDF_SymbolSize_Label            1002
#define IDF_dismiss_plot_options        1003
#define IDF_Axes_Colour                 1004
#define IDF_bin_label                   1005
#define IDF_Bin_Group                   1006
#define IDF_binning                     1007
#define IDF_Colour_Group                1008
#define IDF_DifferenceData_Colour       1009
#define IDF_ObservedData_Colour         1010
#define IDF_TickMark_Colour             1011
#define IDF_CalculatedData_Colour       1012
#define IDF_PeakFitting_Colour          1013
#define IDF_ErrorBar_Check              1014
#define IDF_SymbolSize                  1015
#define IDF_CharacterSize_Label         1016
#define IDF_CharacterSize               1017
#define IDF_Structural_Information_tab  1018
#define IDF_HPSL_Grid                   1019
#define IDF_Peak_Positions_Grid         1020
#define ISS1                            1021
#define IDF_LabX_Source                 1022
#define IDF_SynX_Source                 1023
#define IDF_CWN_Source                  1024
#define IDF_TOF_source                  1025
#define IDF_SOurce_Group                1026
#define IDF_xmin_label                  1027
#define IDF_xmax_label                  1028
#define IDF_ymin_label                  1029
#define IDF_ymax_label                  1030
#define IDF_xmin                        1031
#define IDF_ymin                        1032
#define IDF_xmax                        1033
#define IDF_ymax                        1034
#define IDF_Range_Group                 1035
#define IDF_TOF_group                   1036
#define IDF_Flight_Path_Label           1037
#define IDF_2theta_label                1038
#define IDF_wavelength1                 1039
#define IDF_TAB1                        1040
#define IDF_2theta0                     1041
#define IDF_flight_path                 1042
#define IDF_Data_Download               1043
#define IDF_CW_group                    1044
#define IDF_Wavelength_Menu             1045
#define IDF_radiation_label             1046
#define ID_PWa_DF_Open                  1047
#define IDF_SA_finish                   1048
#define IDF_lattice_constant_group      1049
#define IDF_Crystal_system_group        1050
#define IDF_Space_Group_Group           1051
#define IDF_a_latt_label                1052
#define IDF_b_latt_label                1053
#define IDF_c_latt_label                1054
#define IDF_alp_latt_label              1055
#define IDF_bet_latt_label              1056
#define IDF_gam_latt_label              1057
#define IDF_a_latt                      1058
#define IDF_b_latt                      1059
#define IDF_c_latt                      1060
#define IDF_alp_latt                    1061
#define IDF_bet_latt                    1062
#define IDF_gam_latt                    1063
#define IDF_Crystal_System_Menu         1064
#define IDF_Space_Group_Menu            1065
#define ISS2                            1066
#define ISS3                            1067
#define ISS4                            1068
#define ISS5                            1069
#define ISS6                            1070
#define IDF_gamm1_label                 1071
#define IDF_Widths_Tab                  1072
#define IDF_PeakShape_Explanation       1073
#define IDF_Sigma_Grid                  1074
#define IDF_Gamma_Grid                  1075
#define IDF_HMSL_Grid                   1076
#define IDF_Gamma1                      1077
#define IDF_Gamma2                      1078
#define IDF_gamm2_label                 1079
#define IDF_Gamma_label                 1080
#define IDF_Sigma_label                 1081
#define IDF_Sigma1                      1082
#define IDF_sigma1_label                1083
#define IDF_sigma2                      1084
#define IDF_sigma2_label                1085
#define IDF_sup2_1                      1086
#define IDF_sup2_2                      1087
#define IDF_sup2_3                      1088
#define IDF_HMSL_label                  1089
#define IDF_HMSL1                       1090
#define IDF_HPSL_label                  1091
#define IDF_HPSL1                       1092
#define ISS7                            1093
#define ISS8                            1094
#define IDF_a_refine                    1095
#define IDF_zeropt_refine               1096
#define IDF_c_refine                    1097
#define IDF_alp_refine                  1098
#define IDF_bet_refine                  1099
#define IDF_gam_refine                  1100
#define IDF_b_refine                    1101
#define IDF_a_refine_label              1102
#define IDF_b_refine_label              1103
#define IDF_c_refine_label              1104
#define IDF_alp_refine_label            1105
#define IDF_bet_refine_label            1106
#define IDF_gam_refine_label            1107
#define IDF_zeropt_label                1108
#define IDF_CellRefinement_Label        1109
#define IDF_SA_Project_Name             1110
#define IDF_ZM_allpars                  1111
#define IDF_SA_project_name_label       1112
#define IDB_SA_Project_Browse           1113
#define IDF_ZMatrix_file1               1114
#define IDF_ZMatrix_file2               1115
#define IDF_ZMatrix_file3               1116
#define IDF_ZMatrix_file4               1117
#define IDF_ZMatrix_file5               1118
#define IDB_ZMatrix_Browse1             1119
#define IDB_ZMatrix_Browse2             1120
#define IDB_ZMatrix_Browse3             1121
#define IDB_ZMatrix_Browse4             1122
#define IDB_ZMatrix_Browse5             1123
#define IDF_ZM_pars1                    1124
#define IDF_ZM_pars2                    1125
#define IDF_ZM_pars3                    1126
#define IDF_ZM_pars4                    1127
#define IDF_ZM_pars5                    1128
#define IDF_ZM_file_check1              1129
#define IDF_ZM_file_check2              1130
#define IDF_ZM_file_check3              1131
#define IDF_ZM_file_check4              1132
#define IDF_ZM_file_check5              1133
#define IDF_ZM_file_label               1134
#define IDF_ZM_allpars_label            1135
#define IDB_SA2_back                    1136
#define IDB_SA1_next                    1137
#define IDF_SA1_picture                 1138
#define IDB_SA2_next                    1139
#define IDF_SA2_picture                 1140
#define IDF_SA2_label                   1141
#define IDF_SA3_picture                 1142
#define IDB_SA3_back                    1143
#define IDB_SA3_finish                  1144
#define IDF_SA3_cancel                  1145
#define IDF_SA2_cancel                  1146
#define IDF_SA_T0_trackbar              1147
#define IDF_SA_Tredrate_trackbar        1148
#define IDF_SA_NS_trackbar              1149
#define IDF_SA_NT_trackbar              1150
#define IDF_SA_T0                       1151
#define IDF_SA_NS                       1152
#define IDF_SA_NT                       1153
#define IDF_SA_T0_label                 1154
#define IDF_SA_TRR_label                1155
#define IDF_SA_TRR_label2               1156
#define IDF_SA_TRR_label3               1157
#define IDF_SA_Moves                    1158
#define IDF_SA_NS_label                 1159
#define IDF_SA_NT_label                 1160
#define IDF_SA_T0_label1                1161
#define IDF_SA_cool_label               1162
#define IDF_SA_RandomSeed1              1163
#define IDF_SA_RandomSeed3              1164
#define IDF_SA_RandomSeed2              1165
#define IDF_SA_Simplex_Button           1166
#define IDF_SA_move_distribution        1167
#define IDF_T_picture                   1168
#define IDF_minchisq_picture            1169
#define IDF_prochisq_picture            1170
#define IDF_avchisq_picture             1171
#define IDF_SA_Pause_Button             1172
#define IDF_SA_Stop_Button              1173
#define IDF_SA_Play_Button              1174
#define IDF_SA_Reanneal_Button          1175
#define IDF_SA_total_moves_label        1176
#define IDF_SA_zero_move_label          1177
#define IDF_SA1_cancel                  1178
#define IDF_SA_Tredrate                 1179
#define IDB_PawRef_Save                 1180
#define IDF_SAMove_picture              1181
#define IDF_minchi2_label               1182
#define IDF_avchi2_label                1183
#define IDF_profchisq_label             1184
#define IDF_profchi2_label              1185
#define IDF_profile_chisq2              1186
#define IDF_SATotalMoves_picture        1187
#define IDF_SA_move_type                1188
#define IDF_iteration_moves_label       1189
#define IDF_TBarGroup1                  1190
#define IDF_TBarGroup2                  1191
#define IDF_TBarGroup3                  1192
#define IDF_TBarGroup4                  1193
#define IDF_SA_Eject_Button             1194
#define IDF_SA_NewAnneal_Button         1195
#define IDF_PW1_Back                    1196
#define IDF_SA_move_type2               1196
#define IDF_PW01_Text1                  1197
#define IDF_SA_move_type3               1197
#define IDB_SA_Project_Open             1198
#define IDF_PW_Option1                  1199
#define IDF_PW_Data_fFilename           1200
#define IDF_PW_DataFileName_String      1201
#define ID_PW_DF_Browse                 1202
#define IDF_WelcomeWizard               1203
#define IDF_PW_Logo1                    1204
#define IDF_PW0_Next                    1205
#define IDF_PW0_Back                    1206
#define IDF_PW_Logo2                    1207
#define IDF_PW_Logo3                    1208
#define IDF_PW1_Next                    1209
#define ID_PW_DF_Open                   1210
#define IDF_PW1_Skip                    1211
#define IDF_PW2_Back                    1212
#define IDF_PW2_Next                    1213
#define IDB_SA_Project_Import           1214
#define IDF_PW2_Skip                    1215
#define IDF_PW0_Skip                    1216
#define IDF_PW_lattice_constant_group   1217
#define IDF_PW_Crystal_system_group     1218
#define IDF_PW_Space_Group_Group        1219
#define IDF_PW_a_latt_label             1220
#define IDF_PW_alp_latt_label           1221
#define IDF_PW_a_latt                   1222
#define IDF_PW_alp_latt                 1223
#define IDF_PW_b_latt_label             1224
#define IDF_PW_bet_latt_label           1225
#define IDF_PW_b_latt                   1226
#define IDF_PW_bet_latt                 1227
#define IDF_PW_c_latt_label             1228
#define IDF_PW_gam_latt_label           1229
#define IDF_PW_c_latt                   1230
#define IDF_PW_gam_latt                 1231
#define IDF_PW_Crystal_System_Menu      1232
#define IDF_PW_Space_Group_Menu         1233
#define IDF_PW_Source_Group             1234
#define IDF_PW_LabX_Source              1235
#define IDF_PW_SynX_Source              1236
#define IDF_PW_CWN_Source               1237
#define IDF_PW_TOF_source               1238
#define IDF_PW_Data_Group               1239
#define IDF_PW_CW_group                 1240
#define IDF_PW_wavelength1              1243
#define IDF_PW_radiation_label          1245
#define IDF_PW_Wavelength_Menu          1246
#define IDF_PW_TOF_group                1247
#define IDF_PW_Flight_Path_Label        1248
#define IDF_PW_flight_path              1249
#define IDF_PW_2theta_label             1250
#define IDF_PW_2theta0                  1251
#define IDF_PW_Option2                  1252
#define IDF_PW_Option3                  1253
#define IDF_PW_Option4                  1254
#define IDF_PW_Option_Group             1255
#define IDF_PW_Logo4                    1256
#define IDF_PW3_Back                    1257
#define IDF_PW3_Next                    1258
#define IDF_PW3_Finish                  1259
#define IDF_PWa_Data_Group              1261
#define IDF_PWa_Data_fFilename          1262
#define IDF_PWa_DataFileName_String     1263
#define ID_PWa_DF_Browse                1264
#define IDF_PW_Page2_title              1265
#define IDF_Pawley_Progress_Bar         1266
#define IDF_Pawley_Cycle_Label          1267
#define IDF_Pawley_Cycle_Number         1268
#define IDF_Pawley_Total_Cycles         1269
#define IDF_Pawley_Cycle_Label2         1270
#define IDF_Pawley_Cycle_Refs_Label     1271
#define IDF_Pawley_Cycle_NumRefs        1272
#define IDF_Pawley_Cycle_Pts_Label      1273
#define IDF_Pawley_Cycle_NumPts         1274
#define IDB_PawRef_Reject               1275
#define IDF_Pawley_Cycle_ChiSq          1276
#define IDF_Pawley_Status_Pic           1277
#define IDF_Pawley_Status_Group         1278
#define IDF_Pawley_Cycle_Rwp_Label      1279
#define IDF_Pawley_Cycle_Rwp            1280
#define IDF_Pawley_Cycle_RwpExp_Label   1281
#define IDF_Pawley_Cycle_RwpExp         1282
#define IDF_PawRef_Solve                1283
#define IDF_Pawley_RefNum_Label         1284
#define IDF_Pawley_Refinement_Number    1285
#define IDF_PawRef_RefInts_Check        1286
#define IDB_PawRef_Accept               1287
#define IDF_PawRef_UseInts_Check        1288
#define IDF_PawRef_RefBack_Check        1289
#define IDF_PawRef_NBack_label          1290
#define IDF_IDF_PawRef_NBack            1291
#define IDF_PawRef_RefCell_Check        1292
#define IDF_PawRef_RefZero_Check        1293
#define IDF_clear_zmatrix               1294
#define IDF_PawRef_Line                 1299
#define IDB_PawRef_Skip                 1300
#define IDF_PawRef_Refine               1301
#define IDF_Pawley_Options_Group        1302
#define IDF_PawRefOptionsPicture        1303
#define IDF_Pawley_Cycle_ChiSq_Label1   1317
#define IDF_Pawley_Cycle_ChiSq_Label2   1318
#define IDF_StrInf_Picture              1318
#define IDF_Dismiss_StrInf              1319
#define IDF_PawRef_RefSigm1_Check       1320
#define IDF_PawRef_RefSigm2_Check       1321
#define IDF_PawRef_RefGamm1_Check       1322
#define IDF_PawRef_RefGamm2_Check       1323
#define IDF_CPL_GRID                    1401
#define IDF_LABEL1                      1402
#define IDF_reflections_label           1403
#define IDF_LABEL2                      1404
#define IDF_contributors_label          1405
#define IDF_numatoms_label              1406
#define IDF_reflections                 1407
#define IDF_ProfileType_Radio1          1408
#define IDF_Profile_Zoom_Button         1414
#define IDF_Profile_FullRange_Button    1415
#define IDF_curr_temp_label             1418
#define IDF_min_chisq_label             1419
#define IDF_curr_temp                   1420
#define IDF_min_chisq                   1421
#define IDF_total_moves_label           1422
#define IDF_total_moves                 1423
#define IDF_av_chisq                    1431
#define IDF_avchisq_label               1432
#define IDF_controlfile_label           1434
#define IDF_inputfile_string            1435
#define IDF_inputfile_browse            1436
#define IDF_save_inputfile_button       1437
#define IDF_input_option_tab            1438
#define IDF_saveas_inputfile_button     1440
#define IDF_inputfile_help_button       1441
#define IDF_getinput_group              1442
#define IDF_miscinput_group             1443
#define IDF_savefile_group              1444
#define IDF_Run_button                  1445
#define IDF_space_group_label           1449
#define IDF_spacegp_group               1450
#define IDF_LABEL4                      1458
#define IDF_LABEL5                      1459
#define IDF_LABEL6                      1460
#define IDF_LABEL7                      1463
#define IDF_LABEL11                     1466
#define IDF_LABEL12                     1467
#define IDF_LABEL13                     1468
#define IDF_LABEL14                     1469
#define IDF_LABEL17                     1474
#define IDF_ISEED1                      1475
#define IDF_ISEED2                      1476
#define IDF_ISEED3                      1477
#define IDF_npar_label                  1478
#define IDF_npar                        1479
#define IDF_parameter_grid              1480
#define IDF_inputdata_group             1484
#define IDF_reffile_label               1485
#define IDF_pikfile                     1486
#define IDF_reffile_browse_button       1487
#define IDF_nfrag                       1488
#define IDF_zmatrixfile_grid            1489
#define IDF_contributors                1491
#define IDF_numatoms                    1492
#define IDF_Pause_Annealing             1495
#define IDF_Anneal_LogY                 1497
#define IDF_Status_tab                  1498
#define IDF_Anneal_LinY                 1499
#define IDF_Status_Graph                1500
#define IDF_Profile_Plot                1501
#define IDF_peakcont_label              1502
#define IDF_ProfileType_Radio2          1503
#define IDF_pikfile_browse_button       1504
#define IDF_reffile                     1505
#define IDF_hcvfile                     1507
#define IDF_hcvfile_browse_button       1508
#define IDF_corrint_label               1509
#define IDF_correlations_label          1510
#define IDF_correlations                1511
#define IDF_profile_chisq               1512
#define IDF_profile_chisq_label         1513
#define IDF_Viewer                      1514
#define ID_ICON1                        20001
#define ID_BITMAP1                      20002
#define ID_BITMAP2                      20003
#define ID_BITMAP3                      20004
#define ID_BITMAP4                      20005
#define ID_BITMAP5                      20006
#define ID_BITMAP6                      20007
#define ID_BITMAP7                      20008
#define ID_BITMAP8                      20009
#define ID_BITMAP9                      20010
#define ID_BITMAP10                     20011
#define ID_ICON2                        20012
#define ID_ICON3                        20013
#define ID_STRING001                    20014
#define ID_STRING002                    20015
#define ID_STRING003                    20016
#define ID_STRING004                    20017
#define ID_STRING005                    20018
#define ID_STRING006                    20019
#define ID_STRING007                    20020
#define ID_STRING008                    20021
#define ID_STRING009                    20022
#define ID_STRING010                    20023
#define ID_STRING011                    20024
#define ID_STRING012                    20025
#define ID_STRING013                    20026
#define ID_STRING014                    20027
#define IDR_MENU1                       30001
#define IDR_MENU2                       30002
#define ID_TOOLBAR1                     30102
#define ID_FILE                         40001
#define ID_FILE_PRINT                   40005
#define ID_FILE_EXIT                    40006
#define ID_HELP                         40007
#define ID_HELP_ABOUT                   40008
#define ID_Structure_Solution_Mode      40010
#define ID_ViewMenu                     40011
#define ID_import_xye_file              40014
#define ID_get_peak_positions           40017
#define ID_import_dpj_file              40021
#define ID_Druid_Mode_Menu              40022
#define ID_Peak_Fitting_Mode            40023
#define ID_get_lattice_constants        40024
#define ID_get_peak_widths              40025
#define ID_import_data                  40026
#define ID_import_pro_file              40027
#define ID_Default_Mode                 40028
#define ID_get_peak_intensities         40030
#define ID_help_about_Polyfitter        40031
#define ID_PolyFitter_Help              40032
#define ID_Polyfitter_Tips              40033
#define ID_Level1_Tips                  40034
#define ID_Level2_Tips                  40035
#define ID_Level3_Tips                  40036
#define ID_Level0_Tips                  40037
#define ID_Pawley_Refinement_Mode       40040
#define ID_get_crystal_symmetry         40041
#define ID_get_data_properties          40042
#define ID_Options                      40048
#define ID_plot_options                 40049
#define ID_import_ccl_file              40104
#define ID_Exit                         40112

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        114
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
