      LOGICAL CELLOK,WVLNOK,SPGPOK
      COMMON /STATLOG1/ CELLOK,WVLNOK,SPGPOK
      Integer DataSetChange
      COMMON /STATLOG2/ DataSetChange
      LOGICAL SkipPawleyRef
      Integer NumPawleyRef,NumInternalDSC
      common /qpcommon/ SkipPawleyRef,NumPawleyRef,NumInternalDSC
      integer IRadOption,INWOption
      common /wizoptions/ IRadOption,INWOption
      integer NumberSGTable
      common /NSGTCMN/ NumberSGTable
      integer XBSWidth,XBSHeight,XBSColours
      common /SCREENPARS/ XBSWidth,XBSHeight,XBSColours
      integer WRWidth,WRHeight,WRXPos,WRYPos
      common /WROOTPARS/ WRWidth,WRHeight,WRXPos,WRYPos
      logical FromPawleyFit
      common /SAOrigins/ FromPawleyFit


      

